services:
  - type: web
    name: guias-sena
    env: python
    region: oregon  # puedes cambiarlo a ohio o frankfurt si prefieres
    plan: free

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"

    envVars:
      - key: FLASK_ENV
        value: production
      - key: MONGO_URI
        value: "mongodb+srv://adminSena:CTPIADSO@cluster0.tzgka8b.mongodb.net/guiasDB?retryWrites=true&w=majority&appName=Cluster0"
      - key: SECRET_KEY
        value: "clave_secreta_segura"